# 本番環境（PostgreSQL - Supabase）
spring.datasource.url=jdbc:postgresql://db.ptutslhumzqzullhydxo.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.frontend.origin=https://errorhub-self.vercel.app